from youtube_transcript_extractor.models import CaptionSegment, TranscriptDocument
from youtube_transcript_extractor.normalize import (
    deduplicate_segments,
    fidelity_warnings,
    format_timestamp,
    render_document,
)


def segment(text, start, duration=1):
    return CaptionSegment(
        text=text,
        start_seconds=start,
        duration_seconds=duration,
    )


def document(segments):
    return TranscriptDocument(
        video_id="dQw4w9WgXcQ",
        source_url="https://youtu.be/dQw4w9WgXcQ",
        title="A Test Video",
        author="Test Author",
        language_code="en",
        language_name="English",
        is_generated=True,
        segments=segments,
    )


def test_deduplicate_segments_removes_rolling_caption_overlap():
    result = deduplicate_segments(
        [
            segment("Hello there, how are you", 0),
            segment("how are you today", 1),
        ]
    )
    assert [item.text for item in result] == [
        "Hello there, how are you",
        "today",
    ]


def test_deduplicate_segments_removes_repeated_window():
    result = deduplicate_segments(
        [segment("This is repeated", 0), segment("This is repeated", 1)]
    )
    assert [item.text for item in result] == ["This is repeated"]


def test_render_document_includes_metadata_and_timestamp_links():
    output = render_document(document([segment("Hello world.", 65)]), True)
    assert "# A Test Video" in output
    assert "Captions: autogenerated" in output
    assert "[1:05](https://youtu.be/dQw4w9WgXcQ?t=65)" in output


def test_format_timestamp_supports_hours():
    assert format_timestamp(3661) == "1:01:01"


def test_fidelity_warnings_notice_shortened_output():
    warnings = fidelity_warnings(
        "# Transcript\n\nSource: https://example.com\n\nHello there, this is a long sentence.",
        "# Transcript\n\nSource: https://example.com\n\nHello.",
    )
    assert warnings
